version: '3'
services:
  web:
    image: mindovermiles262/leanote:latest
    environment:
      - APP_SECRET=${APP_SECRET}
      - SITE_URL=${SITE_URL}
    ports:
      - "${LEANOTE_PORT:-8080}:8080"
    depends_on:
      - db
    
  db:
    image: mongo
    volumes:
      - ./seed:/seed
